### ISSUE TITLE
binary file source/sink - mmap

### ISSUE THREAD

**Issue by guruofquality** [pothosware/PothosBlocks#1]
implement zero copy mmap based reader and writer. We should be able to pass around mapped pages with the buffer management api. It could be advantageous -- needs benchmarking as well.
- Example: https://www.cs.purdue.edu/homes/fahmy/cs503/mmap.txt
- Windows equivalent: CreateFileMapping + VirtualAlloc?

**Comment by ncorgan** [comment]
WIP branch: https://github.com/pothosware/PothosBlocks/tree/wip/mmap
