### ISSUE TITLE
StreamToPacket stalls.

### ISSUE THREAD

**Issue by ashley-b** [pothosware/PothosBlocks#46]
I have noticed when running Waveform Source into StreamToPacket it stalls, when its is free running (with not start or end Labels).
I have noticed the block code is consuming the Packet length, I assume this is meant to be the elements().
I did try this change and the block no longer stalls but it produces garbled data after a while.

https://github.com/pothosware/PothosBlocks/blob/9d88b038dd5a9cf864f437e4a930171d343340fa/packet/StreamToPacket.cpp#L227

Also should inputPort->consume do some sanity check to see if there is that much data to consume?

**Comment by guruofquality** [comment]
Sorry about that. Its fixed on master. I was just writing some release notes for 0.6 about how not to cause this particular bug in block code, and I did it myself anyway.
