### ISSUE TITLE
Feature request: source block that fills output buffers with single parameterized value

### ISSUE THREAD

**Issue by ncorgan** [pothosware/PothosBlocks#50]

**Comment by guruofquality** [comment]
The waveform source with a constant? Or something more complicated than that?

**Comment by ncorgan** [comment]
WaveformSource with a constant fills the buffer with 1.0 and takes in an amplitude. This could theoretically be used to get to any value, but what I'm talking about is more like this: https://github.com/ncorgan/PothosArrayFire/blob/master/Source/Constant.cpp

Support all types and directly specify the constant to use.

**Comment by ncorgan** [comment]
This should be simple to implement, so unless you have any objections, I can knock it out tonight.

**Comment by guruofquality** [comment]
sure, go for it
