### ISSUE TITLE
Blocks

### ISSUE THREAD

**Issue by dangithubs** [pothosware/PothosBlocks#60]
Hi Guys,

Just getting started with Pothos and I have been learning about LoRa and experimenting with it.

I wanted to see if I could modify one of the demo Pothos flows which simulates generating signals and then reading them back in and decoding them (https://github.com/myriadrf/LoRa-SDR/tree/master/examples/lora_simulation.pth)

I was trying to change it so the user could enter a word in and have it generate a signal and have it decode their word. Currently LoRa Test Gen just generates random numbers and then stores each of them in the payload so you essentially get a counter.

The demo I was looking at had LoRa Test Gen >> Pacer >> LoRa Encoder >> LoRa Mod etc 

I tried plugging in a chat box instead of LoRa Test Gen like this :

Chat Box >> Pacer >> LoRa Encoder >> LoRa Mod

but I think that fails because it is not generating a packet correctly. 

My question is, how do I create a packet and place a word in the payload which I believe is required for my planned above modification to work.

Or do I need to find the code for LoRa Test Gen and then try and learn C in order to compile my own version of LoRa Test Gen ?

Any help would be appreciated.

Dan

**Comment by guruofquality** [comment]
I would take a look at the project here, thats where the blocks come from if you want to see the source: https://github.com/myriadrf/LoRa-SDR/
